### PR TITLE
Iterate over all available interfaces

### LINKED ISSUE #260: Hard-coded eth0 interface in getMACAddress implementation for Linux
The Linux implementation assumes that the network interface is called `eth0` and it doesn't support the index argument
(https://github.com/modelica/Modelica_DeviceDrivers/blob/1b988c000dc8b8f86fcfbc011938949e5bdc6467/Modelica_DeviceDrivers/Resources/Include/MDDUtilitiesMAC.h#L117)

- Even for wire-based ethernet interfaces, the name for the interface in Linux is not always `eth0`, hence even if a Linux machine has an ethernet adapter, the function might not correctly retrieve its MAC address.
- What seems more useful is to iterate over all the available interfaces. That is what the Windows implementation does.
- Thinking about it, it seems useful to have a Modelica function that returns an array of all the network interface MAC addresses available on the machine.

### PR DESCRIPTION
**Pull request by tbeu**
The Linux implementation of MDD_utilitiesGetMACAddress iterates over all available interfaces.

Close #260

### CODE REVIEW

**Comment by tbeu** [comment]
Test model
```mo
model MACTest
  parameter Integer n=5;
  String s[n];
  equation
    when sample(0.1,0.1) then
    for i in 1:n loop
      s[i] = Modelica_DeviceDrivers.Utilities.Functions.getMACAddress(i);
      Modelica.Utilities.Streams.print("s[" + String(i) + "]: " + s[i]);
      end for;
    end when;
end MACTest;
```

**Comment by bernhard-thiele** [comment]
Tested it on my Linux machine and when calling `getMACAddress(1)` I get the strange return string `FFF70-FFFFFF4B-FFF` (not a MAC address at all and completely different to what I have). If I do `getMACAddress(2)` I get an empty string, although the machine has two interfaces.

**Comment by tbeu** [comment]
That is strange. This is what I see on my Linux VM:
```
s[1]: 00-15-5D-04-41-2B
s[2]: 
s[3]: 
s[4]: 
s[5]: 
```
Can you please print the original sa_data byte array, that is before converting it to unsigned inst for string concatenation? Does it help if casted to uint8 instead uint32?

**Comment by tbeu** [comment]
Reading http://www.cplusplus.com/reference/cstdio/printf/ again on the `.number` precision specifier: 
>  The value is not truncated even if the result is longer.

That is one source of unexpected behaviour. Casting to uint8_t should help.

**Comment by bernhard-thiele** [comment]
With the last fix I get my machine's correct MAC address :+1: .

However, it seems that the code only finds interfaces that are connected. That should be fine for the mqtt use-case for that function, but we should check if that is the same behavior as in the Windows implementation and also document that restriction.

**Comment by bernhard-thiele** [comment]
I just tested in Windows and it seems the behavior is indeed different, in the sense that in Windows also unconnected interfaces are found. However, apart from that detail everything works now and the rest can be fixed at a later time.

**Pull request merged**
