### PR TITLE
Fix CompatibilityDefs.h

### PR DESCRIPTION
**Pull request by tbeu**
* Only export symbols if `MDDSHAREDLIBRARY` is set explicitly. This is the case for the SimulationX specific wrappers.
* Can set `DllExport` to `static` otherwise to avoid a potential linker issue with inclusion by multiple modules

### CODE REVIEW

**Comment by tbeu** [comment]
In which case do you require MDD symbols exported for Linux shared object? If `DllExport` is not defined to something, it falls back to `extern` (which is the default). This makes trouble for the (artificial) scenario of two different modules including the same MDD header.

**Comment by bernhard-thiele** [comment]
At the moment there is no *.so generated for Linux (since everything is used as header-only library), but the mechanism is meant to allow generating a DLL and a SO from the same source. In that sense it would be very confusing to use definitions that would prevent that. If we need that logic, it should be provided by its own mechanism that makes the intention clear when reading the code.

Besides that,  we don't really know how Modelica tools will organize the generated code into (different) compilation units. Dymola splits up the source code if the generated code gets large in order to reduce the size of compilation units, OMC splits it up, too. Probably, that won't be a problem, since I guess that the external C code will only be accessed in the compilation unit there it becomes a part of. However, I don't know for sure. So I think that having functions as static in the case of using the code as header-only is a good idea, but it would require a bit of careful testing so that no (large) models break in unexpected ways.

**Comment by tbeu** [comment]
OK, I updated the PR accordingly.

**Comment by tbeu** [comment]
Can you test if defining `DllExport` as `__attribute__((visibility("default")))` for Linux shared object works as expected?

**Comment by bernhard-thiele** [comment]
Never used that attribute before. What improvement is expected by using `__attribute__((visibility("default")))`? Is this different to simply not having it?

**Comment by tbeu** [comment]
It only makes a difference if you compile with `-fvisibility=hidden`, see https://gcc.gnu.org/wiki/Visibility

**Comment by tbeu** [comment]
> Can you test if defining `DllExport` as `__attribute__((visibility("default")))` for Linux shared object works as expected?

Ah, `DllExport` is not used at all for the Linux implementations.

**Comment by tbeu** [comment]
Sorry, my bad. DllExport = static does not work for Resources\Include\MDDSpaceMouse.h, where MDD_spaceMouseGetData is not a static function, but imported from MDDSpaceMouse.lib or MDDSpaceMouseStatic.lib. This needs to be changed to DllExport = EXTERN then.

**Pull request merged**
