### PR TITLE
Rewrite shared memory buffer synchronization (Win)

### PR DESCRIPTION
**Pull request by tbeu**
* Remove 8 byte buffer overhead for lock and buffer size
* Use semaphore (instead of lock within shared memory buffer) consistent with Linux implementation

This PR supersedes #136.

### CODE REVIEW

**Comment by bernhard-thiele** [comment]
Was there any problem with the code before, that is fixed by this PR, or is it basically the two stated improvements (I found the code before easier to read and  I liked that it was more commented)?

**Comment by tbeu** [comment]
> Was there any problem with the code before, that is fixed by this PR, or is it basically the two stated improvements (I found the code before easier to read and I liked that it was more commented)?

It is written in the commit message. There was an undocumeneted and probably unexpected 8 byte header making the Windows code inconsitent with the Linux implementation. That is now fixed by this b5af8e636942eb1b309b5908908600a369e0a570

**Comment by tbeu** [comment]
I also removed the macros by purpose since they are nowhere else used in the external code.
I also removed the commentss by purpose since it is copied from MSDN only and nowhere else used in the external Win code

**Comment by tbeu** [comment]
The other option would be to adapt the Linux code, e.g. get rid of the semaphore and use the 8 byte header for sync.

**Comment by bernhard-thiele** [comment]
> It is written in the commit message. There was an undocumented and probably unexpected 8 byte header making the Windows code inconsitent with the Linux implementation.

The implementation is different in Linux and Windows, but the interface is the same (the differences in implementation are encapsulated). I don't see unexpected behaviour when using the module. 

I'm not against a semaphore based approach, but I'm always reluctant to make changes to code that seems to have worked before and which has some established confidence from use over an extended period of time. On the one hand, this means to invest time in it (not only writing the code but also reviewing and testing), on the other hand, It happens easily to introduce new bugs. 

I've spent now quite some time looking at the code and probably your changes are equally fine, indeed, probably nicer, since you do without macros and I'm not a macro fan. However, I've not tested the code, I may have overlooked something. I'm just reluctant to replace code which has gained confidence from use with something that might be a bit nicer, but brings not much tangible improvements, while having the potential of introducing new bugs and calling for additional work for reviewing and testing. Hence, unless I have overlooked something, I would rather prefer to keep the current code base.

**Comment by tbeu** [comment]
The current implementation was never documented and I doubt it was used at all, as otherwise users would have stumbled upon that >=8 byte header. So I doubt there will be external code at users applications that worked together with the current Win implementation of SharedMemoryRead or SharedMemoryWrite, especially because of the bug reported and fixed by #133 (that it was more than 8 byte overhead).
The proposed code makes life easier for you (and users) since there is now a semaphore used in the Win and Linux implementation. And you can be sure I tested the code as otherwise I would not have observed #133.

**Comment by tbeu** [comment]
Edit: Wrong cross-reference. Should be #136.

**Comment by bernhard-thiele** [comment]
Yes, this is a bad error. I didn't see it by comparing with this patch, because everything is solved very differently anyway. It is of course visible in #136. 

Sorry, calling that error an 8 byte buffer overhead in your commit message was misleading for me. It's not the problem that memory isn't used efficiently here, It's a pointer arithmetic error.

I was additionally reluctant, because simply removing a little bit of overhead is not worth risking that potentially existing third party code, which relies on the overhead, is not working any more. However, since fixing the error will anyway have an impact on existing applications, one can also change it more drastically, as you do in this PR.

We need to make sure in the next release notes that we explicitly warn from the possible implications of that fix on user code and hope that users read it.

**Comment by tbeu** [comment]
> Yes, this is a bad error.

True. I called it an embarrassing error.

You can use the milestone feature to set issues to milestones, thus it hopefully will not be forgotten when making the release noes.

**Comment by tbeu** [comment]
> We need to make sure in the next release notes that we explicitly warn from the possible implications of that fix on user code and hope that users read it.

So, yes it both is a fix and a backwards-compatibility breaking one, which according to semver requires an increment in the major number. But as I said, I doubt that SharedMemory was used at all at user's applications.

**Pull request merged**
