### PR TITLE
Make the double buffer a thread-local variable of the UDP receive thr…

### PR DESCRIPTION
**Pull request by tbeu**
…ead (Win)

### CODE REVIEW

**Comment by bernhard-thiele** [comment]
Generally, I like it if required memory allocations are collected in the external object constructor. Why change it?

**Comment by tbeu** [comment]
> Why change it?

To have it consistent with the serial port I/O.

**Comment by bernhard-thiele** [comment]
- I think it was your latest change for the serial port that allocated memory in the receiving thread. It was not done before and the Linux version solves it differently and collects all the buffers within the external object
- Yes, one saves a few bytes if one uses the object only for sending. In that case one still "wastes" memory because the object still has a receiving buffer that isn't used for sending. However, for PCs, saving a few bytes here doesn't really matter (maybe one needs to reconsider if using the code on a very restricted embedded system, but that would probably not run Windows). I rather prefer to keep a clearly arranged structure in which all memory allocation is done the constructor and freeing of memory in the destructor (I would prefer that for the serial port, too).

**Comment by tbeu** [comment]
> I think it was your latest change for the serial port that allocated memory in the receiving thread.

Indeed, I like it the other way round, to only allocate what is really necessary. You can of course revert that bit in serial port I/O to allocate all again in the ctor like it was before.

**Comment by tbeu** [comment]
Reopen before I forget about it again: Either make serial port  consistent to UDP or the other way round.

**Comment by tbeu** [comment]
OK.

**Pull request closed without merging**
