### PR TITLE
Downgrade to MLS 3.2

### PR DESCRIPTION
**Pull request by tbeu**
See #170

### CODE REVIEW

**Comment by bernhard-thiele** [comment]
Why? From #170 I guess that SimulationX can't load the current master, because of the impure keyword. However, I'm not sure whether the OM embedded code generation needs this keyword. @sjoelund Can the OM embedded code generation work without it?

**Comment by sjoelund** [comment]
It doesn't need the keyword; the annotation works. But the library uses other 3.3 features (synchronous), so it should be fine to use the impure keyword as well.

**Comment by tbeu** [comment]
For the synchronous stuff always exist sampled alternatives based on MLS 3.2.

**Comment by bernhard-thiele** [comment]
I merged it. Seems the annotation is currently the only way to cater for all tools.

**Pull request merged**
