### PR TITLE
Change license to BSD 3-Clause License

### LINKED ISSUE #238: Adapt new Modelica Association license (BSD-3 clause)
The library is still *Licensed by the Modelica Association under the Modelica License 2*. Since the library is within the `modelica` user group and therefore under the umbrella of the Modelica Association, the new licensing model of the Modelica Association should be adapted (i.e., BSD-3 clause). This would help for future integration into the Modelica Standard Library (MSL).

@christoff-buerger I copied the issue text from https://github.com/modelica/Modelica_Synchronous/issues/35.

### PR DESCRIPTION
**Pull request by tbeu**
Close #238

### CODE REVIEW

**Comment by beutlich** [comment]
The main contributors @tbellmann and @bernhard-thiele as well as the chairman of the Modelica Association @MartinOtter should approve this PR to authorize the license change.

**Comment by tbeu** [comment]
@it-cosmos @vwaurich @sjoelund Can you please comment if you agree on the proposed license change.

**Comment by bernhard-thiele** [comment]
I agree with changing the license to the new BSD 3-Clause License which is the new license adapted by the Modelica Associations for the MSL.

**Comment by tbellmann** [comment]
I also agree with changing the license to the new BSD 3-Clause License.

**Comment by MartinOtter** [comment]
I agree with changing the license to the new BSD 3-Clause License which is the new license adapted by the Modelica Associations for the MSL.

**Comment by sjoelund** [comment]
I agree with changing the license to the new BSD 3-Clause License which is the new license adapted by the Modelica Associations for the MSL.

**Comment by vwaurich** [comment]
I agree with changing the license to the new BSD 3-Clause License.

**Comment by it-cosmos** [comment]
I agree with changing the license to the new BSD 3-Clause License.

**Pull request merged**
