### PR TITLE
Add utility function to retrieve MAC address

### PR DESCRIPTION
**Pull request by tbeu**
Tested with Cygwin, MinGW, MSVC and GCC on Linux.

As mentioned in https://github.com/modelica/Modelica_DeviceDrivers/pull/244#issuecomment-415655633 I needed to split the utility functions in separate header files to avoid linker errors,

TODO: Add libIPHlpApi.a to the Linux libraries

### CODE REVIEW

**Comment by tbeu** [comment]
Does it fail to build or to simulate qith OMC on Win?

**Comment by bernhard-thiele** [comment]
The build fails. I get errors like

```
In file included from C:/OMDev/tools/msys/mingw64/x86_64-w64-mingw32/include/mprapi.h:10:0,
                 from C:/OMDev/tools/msys/mingw64/x86_64-w64-mingw32/include/iprtrmib.h:9,
                 from C:/OMDev/tools/msys/mingw64/x86_64-w64-mingw32/include/IPHlpApi.h:17,
                 from D:/ModelicaLibs/Modelica_DeviceDrivers/Modelica_DeviceDrivers/Resources/Include/MDDUtilitiesMAC.h:20,
                 from Testme_includes.h:4,
                 from Testme_functions.c:6:
C:/OMDev/tools/msys/mingw64/x86_64-w64-mingw32/include/ras.h:440:24: error: expected declaration specifiers or '...' before '*' token
   typedef VOID (WINAPI *RASDIALFUNC)(UINT,RASCONNSTATE,DWORD);
```

This can be avoided by adding a `#define VOID void` into the header. In that case my example model

```modelica
model Testme
  String s;
equation
when sample(0.1,0.1) then
  s = Modelica_DeviceDrivers.Utilities.Functions.getMACAddress();
  Modelica.Utilities.Streams.print(s);
end when;
end Testme;
```

compiles (though there are some linker issues):

```
C:/OMDev/tools/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .rsrc merge failure: duplicate leaf: type: 18 (MANIFEST) name: 2 lang: 409
C:/OMDev/tools/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .rsrc merge failure: differing directory versions
```

However, the simulation process crashes immediately.

**Comment by tbeu** [comment]
f579ab61ca60cd2f6c4b40fe1ec31fbb314bd0a6 fixes one redefinition warning.

I am also about to mark Modelica_DeviceDrivers.Utilities.Functions.getMACAddress as pure function, since normally you will not change physical address of network adapter while M_DD simulation runs. OK to change?

**Comment by bernhard-thiele** [comment]
Do you mean to change it by using the Modelica `pure` prefix or some annotation? If it is the keyword `pure`, shall it be the MLS 3.3 `pure` or MLS 3.4 (which would be a backwards compatibility issue)?

**Comment by tbeu** [comment]
No, I simple want to remove the Impure annotation.

**Comment by bernhard-thiele** [comment]
Sure, makes sense.

**Pull request merged**
