### PR TITLE
Stm32 f4

### PR DESCRIPTION
**Pull request by it-cosmos**
Still AVR garbage has to be cleaned up.
Synchronisation time is max. 1 ms, since HAL.GetTick returns ticks in ms.
Makefile modifies generated c-file Blink_Main.c since is missing. arm-non-eabi does not compile without that fix.

### CODE REVIEW

**Comment by bernhard-thiele** [comment]
@it-cosmos First of all, thanks a lot, for considering to contribute this very nice work to the project!

Just for making sure that you know and agree about it, the license for the Modelica parts of MDD is  [Modelica License 2](https://modelica.org/licenses/ModelicaLicense2), the other (C-)code is a "Simplified BSD License" style license (see Resources/License.txt). Please indicate if you don't want your code to be under these licenses.

Some comments.

- There is currently no documentation on how to use the STM target. Something similar to the documentation given in `Modelica_DeviceDrivers.EmbeddedTargets.AVR` is needed
- There is C-code below the directory `STM32F4/Examples/STM32F4_Discovery/Blink/`. Since this is a Modelica package directory it shouldn't be mixed with other parts. It is a convention in Modelica to put non-Modelica parts below the `Resources` directory. Third party code in MDD is usually collected below `Resources/thirdParty/` in order to keep the IP situation as transparent and clean as possible.
- I will create a branch `STM32F4-feature` for working on this feature before we integrate it into the master

**Comment by bernhard-thiele** [comment]
Merged branch with ae66aeff11a3681057c0d7fa56b76097c27b9d7d into STM32F4-feature branch.

**Comment by it-cosmos** [comment]
I agree with boch licences, Modelica License 2 and the simplified BSD license for C-Code. I proviced documentation withing the Makefile "Modelica_DeviceDrivers/EmbeddedTargets/STM32F4/Examples/STM32F4_Discovery/Blink/Makefile". For consistency it should be moved to Modelica_DeviceDrivers.EmbeddedTargets.STM32F4. It is also for the Makefile recomanded to be below the Resource Dircetory?

**Comment by it-cosmos** [comment]
Shall I close the pull request?

Where will the discussion continue?

**Comment by bernhard-thiele** [comment]
Just created #218 for continuing the discussion so that this PR can be closed.

**Pull request closed without merging**
