### PR TITLE
Handle incomplete messages at serial port

### PR DESCRIPTION
**Pull request by bernhard-thiele**
Related to #117, #119, #127

### CODE REVIEW

**Comment by bernhard-thiele** [comment]
I think that should solve the issue for the Linux part. Any comments?

**Comment by tbeu** [comment]
`serial->nReceivedBytes` should not be accessed outside the mutex.

**Comment by bernhard-thiele** [comment]
Hm, `serial->nReceivedBytes` is only used in its own thread, except for function `MDD_serialPortGetReceivedBytes(..)` which reads it.

One could protect everything by a mutex, but using `MDD_serialPortGetReceivedBytes(..)`, e.g., to check whether enough bytes have been received before doing something is not very robust anyway. There is no guarantee that the number of read bytes doesn't change immediately in the reading thread after the function has been called. This potentially invalidates any condition under which some action would be triggered in the Modelica code part. Maybe its best to just flag it as an unsafe function which might have some use for debugging, but shouldn't be used for anything else.

**Comment by tbeu** [comment]
If `serial->nReceivedBytes` is only used in its own thread, then there is no need to have it in the serial struct. See also https://github.com/modelica/Modelica_DeviceDrivers/issues/127#issuecomment-255952934

**Comment by tbeu** [comment]
Hm, MDD_serialPortGetReceivedBytes is called in the test module (test_MDDSerialPort.c). And this is not only the case for serial port I/O but basically for all other communication drivers. Thus deprecating one, which is fine for me, is not enough. I propose to deprecate all of them.

**Comment by bernhard-thiele** [comment]
Okay, I came up with another solution which should be more useful. `serial->nReceivedBytes` will now contain the sum of all received bytes and its access is protected by a mutex (see commit).

**Pull request merged**
