### PR TITLE
Minor things on spelling and links

### PR DESCRIPTION
**Pull request by tbeu**

### CODE REVIEW

**Comment by tbeu** [comment]
Is this OK to merge?

**Comment by bernhard-thiele** [comment]
It's fine except that I don't like 6ec4d826961a470f8e6ab323c5f868cd88d70319. I prefer keeping the complete link in the text.

**Comment by tbeu** [comment]
Want cherry-pick, revert w/o rewriting or revert with rewriting history?

**Comment by bernhard-thiele** [comment]
Preferable revert with rewriting history

**Comment by tbeu** [comment]
> Preferable revert with rewriting history

Done.

**Pull request merged**
